### ISSUE TITLE
LabelResults specified as object/array while docs site state it is always array

### ISSUE THREAD

**Issue by ysangkok** [UPS-API/api-documentation#159]
Compare current master branch:

```
        LabelResults:
          oneOf:
          - items:
              "$ref": "#/components/schemas/LabelRecoveryResponse_LabelResults"
            type: array
          - "$ref": "#/components/schemas/LabelRecoveryResponse_LabelResults"
```

and

![image](https://github.com/user-attachments/assets/2f99bd72-cd98-4ade-ad3b-0507e139991f)

The image says it is *always* an array. Unlike e.g. the sister element TrackingCandidate which is specified to be either array or object:

> Array of LabelRecoveryResponse_TrackingCandidate (objects) or LabelRecoveryResponse_TrackingCandidate (object)
